"use client"
import AuthProvider from "./context/AuthProvider";
import AuthContext from "./context/AuthProvider";
import TaskContext, { TaskProvider } from "./context/TaskContext";
import "./globals.css";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TaskProvider>{children}</TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
